name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: | 
        mkdir output
        cp style.css output/
        cp favicon.ico output/
    - uses: ./.github/actions/pandoc-conversion-action
      with:
        args: "-s --toc --metadata-file=metadata.yml --css=style.css README.md -o output/index.html"
    - run: |
        eval "$(ssh-agent -a ${SSH_AUTH_SOCK})"
        ssh-add - <<< "${ESSENTIALMUNICH_PRIVATE_KEY}"
        mkdir $HOME/.ssh
        echo "${ESSENTIALMUNICH_HOST}" >> $HOME/.ssh/known_hosts
        rsync -avz --delete output/ essentialmunich@essentialmunich.de:/home/essentialmunich/essentialmunich.de/
      env:
        SSH_AUTH_SOCK: /tmp/ssh-auth.sock
        ESSENTIALMUNICH_PRIVATE_KEY: ${{ secrets.ESSENTIALMUNICH_PRIVATE_KEY }}
        ESSENTIALMUNICH_HOST: ${{ secrets.ESSENTIALMUNICH_HOST }}
