name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: | 
        mkdir output
        cp static/* output/
    - run: echo "::set-output name=now::$(date '+%B %e, %Y')"
      id: date
    - uses: ./.github/actions/pandoc-conversion-action
      with:
        args: "-s --toc --template=template.html --metadata-file=metadata.yml -M date=\"Last updated: ${{ steps.date.outputs.now }}\" --css style.css README.md -o output/index.html"
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output      
